spring.application.name=bff-agendador-tarefas

usuario.url=localhost:8081/usuario
agendador-tarefas.url=localhost:8082/tarefas
notificacao.url=localhost:8083/email
server.port=8084


spring.cloud.openfeign.okhttp.enabled=true

//cron.horario=0/30 0/1 * * * ?

cron.horario=0 0/2 * * * ?


usuario.email=admin@admin.com
usuario.senha=1234